version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8010:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
    networks:
      - pacifiko_net

  node:
    image: node:18
    container_name: node_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: sh -c "npm install && npx vite"
    ports:
      - "5173:5173"
    networks:
      - pacifiko_net
    depends_on:
      - laravel

  python:
    build:
      context: ./data_analysis
      dockerfile: Dockerfile
    container_name: python_scripts
    volumes:
      - .:/app
    networks:
      - pacifiko_net
    tty: true

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pacifiko_test
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - pacifiko_net

networks:
  pacifiko_net:

volumes:
  db_data:
